#!/bin/tcsh 

#raco pollen start
# http://localhost:8080/index.ptree 

echo 'running' 

scribble --html ++xref-in setup/xref load-collections-xref \
#          --redirect-main "http://pre.plt-scheme.org/docs/html/" \
#  "http://docs.plt-scheme.org/" \
          --dest Tmp/ \
          $1.scrbl 

echo 'completely done'

open ~/0Unison/0Web/OnHtDP/Source/Tmp/$1.html
