(!definitely-latex)
(!toc-page 2)
(!toc-entry 0 "1" 5 "node_sec_1" "Monday Morning: Welcome Back")
(!toc-entry 1 "1.1" 5 "node_sec_1.1" "Goals")
(!toc-entry 1 "1.2" 5 "node_sec_1.2" "Example: Functions on Numbers")
(!toc-entry 1 "1.3" 5 "node_sec_1.3" "Example: Images")
(!toc-entry 1 "1.4" 5 "node_sec_1.4" "Example: Structures and Functions on Structures")
(!toc-entry 1 "1.5" 5 "node_sec_1.5" "Example: Lists and Functions on Lists")
(!toc-entry 0 "2" 7 "node_sec_2" "Monday Afternoon: Images, Lists, <strong>N</strong>")
(!toc-entry 1 "2.1" 7 "node_sec_2.1" "Goals")
(!toc-entry 1 "2.2" 7 "node_sec_2.2" "A Notation for Lists")
(!toc-entry 1 "2.3" 8 "node_sec_2.3" "Example: <strong>N</strong>")
(!toc-entry 1 "2.4" 8 "node_sec_2.4" "Example: More on Images")
(!toc-entry 1 "2.5" 8 "node_sec_2.5" "Example: Image Functions")
(!toc-entry 0 "3" 10 "node_sec_3" "Tuesday Morning: Local Definitions")
(!toc-entry 1 "3.1" 10 "node_sec_3.1" "Goals")
(!toc-entry 1 "3.2" 10 "node_sec_3.2" "Local Definitions: Syntax and Semantics")
(!toc-entry 1 "3.3" 10 "node_sec_3.3" "Local Definitions: Go slow!")
(!toc-entry 1 "3.4" 11 "node_sec_3.4" "Local Definitions: Go fast!")
(!toc-entry 1 "3.5" 11 "node_sec_3.5" "Local Definitions: Just Do It")
(!toc-entry 1 "3.6" 11 "node_sec_3.6" "Lexical Scope")
(!toc-entry 0 "4" 13 "node_sec_4" "Tuesday Afternoon: Generative Recursion")
(!toc-entry 1 "4.1" 13 "node_sec_4.1" "Goal")
(!toc-entry 1 "4.2" 13 "node_sec_4.2" "Example: Generating Balloons")
(!toc-entry 1 "4.3" 13 "node_sec_4.3" "Example: Sorting Numbers")
(!toc-entry 1 "4.4" 13 "node_sec_4.4" "Example: Fractals")
(!toc-entry 1 "4.5" 13 "node_sec_4.5" "Generative Recursion: The Design Recipe")
(!toc-entry 0 "5" 15 "node_sec_5" "Wednesday Morning: Creating Abstractions")
(!toc-entry 1 "5.1" 15 "node_sec_5.1" "Goal")
(!toc-entry 1 "5.2" 15 "node_sec_5.2" "Example: Functions are Values, too")
(!toc-entry 1 "5.3" 15 "node_sec_5.3" "Example: Primitives are Values, too")
(!toc-entry 1 "5.4" 15 "node_sec_5.4" "Example: More on Functions")
(!toc-entry 1 "5.5" 15 "node_sec_5.5" "Example: Contracts are People, too")
(!toc-entry 1 "5.6" 15 "node_sec_5.6" "Function have Contracts, too")
(!toc-entry 0 "6" 17 "node_sec_6" "Wednesday Afternoon: Using Abstractions")
(!toc-entry 1 "6.1" 17 "node_sec_6.1" "Goals: 1001 Loops")
(!toc-entry 1 "6.2" 18 "node_sec_6.2" "Examples: Mapping")
(!toc-entry 1 "6.3" 18 "node_sec_6.3" "mapping with lambda, the Ultimate")
(!toc-entry 1 "6.4" 19 "node_sec_6.4" "Example: Filtering")
(!toc-entry 1 "6.5" 19 "node_sec_6.5" "filtering with lambda, the Ultimate")
(!toc-entry 1 "6.6" 20 "node_sec_6.6" "lambda, the ultimate")
(!toc-entry 1 "6.7" 21 "node_sec_6.7" "Example: Building Lists, with lambda")
(!toc-entry 0 "7" 23 "node_sec_7" "Thursday Morning: Some Basic I/O")
(!toc-entry 1 "7.1" 23 "node_sec_7.1" "Goal: Shriram&#8217;s Day of Networking")
(!toc-entry 1 "7.2" 23 "node_sec_7.2" "apply, another powerful loop")
(!toc-entry 1 "7.3" 24 "node_sec_7.3" "Example: Keeping Track of Grades")
(!toc-entry 1 "7.4" 25 "node_sec_7.4" "Input and Output: S-expressions")
(!toc-entry 0 "8" 27 "node_sec_8" "Thursday Afternoon: A Networking Application")
(!toc-entry 0 "9" 28 "node_sec_9" "Friday Morning: Games")
(!toc-entry 1 "9.1" 28 "node_sec_9.1" "Goal")
(!toc-entry 1 "9.2" 28 "node_sec_9.2" "Calling Functions on Events")
(!toc-entry 1 "9.3" 28 "node_sec_9.3" "Example: Flying a Rocket")
(!toc-entry 1 "9.4" 28 "node_sec_9.4" "The Nature of Keystroke Events")
(!toc-entry 1 "9.5" 29 "node_sec_9.5" "Example: Launching a Rocket")
(!toc-entry 0 "10" 31 "node_sec_10" "Friday Afternoon: More on Games")
(!toc-entry 1 "10.1" 31 "node_sec_10.1" "Goal")
(!last-page-number 31)
(!last-modification-time 1096905975)
(!head-line "")
(!foot-line "\\folio")
