#!/bin/tcsh 

scribble --htmls ++xref-in setup/xref load-collections-xref \
          --redirect-main "http://docs.plt-scheme.org/" \
# "http://pre.plt-scheme.org/docs/html/" \
          --dest ~/0Unison/0Web/ \
          Thoughts.scrbl 

open ~/0Unison/0Web/Thoughts/index.html
